name: PR

on: pull_request

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    name: Lint GitHub Action Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check workflow files
        uses: docker://ponylang/shared-docker-ci-actionlint:20230810
        with:
          args: -color

  superlinter:
    name: Lint bash, docker, markdown, and yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint codebase
        uses: docker://github/super-linter:v3.8.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BASH: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_MD: true
          VALIDATE_YAML: true

  verify-changelog:
    name: Verify CHANGELOG is valid
    runs-on: ubuntu-latest
    container:
      image: ponylang/changelog-tool:release
    steps:
      - uses: actions/checkout@v2
      - name: Verify CHANGELOG
        run: changelog-tool verify

  vs-ponyc-release-linux:
    name: Test against recent ponyc release on Linux
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder:release
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: make test config=debug

  vs-ponyc-release-macOS:
    name: Test against recent ponyc release on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: bash .ci-scripts/macOS-install-pony-tools.bash release
      - name: Test
        run: |
          export PATH="$HOME/.local/share/ponyup/bin/:$PATH"
          make test config=debug

  vs-ponyc-release-windows:
    name: Test against recent ponyc release on Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Test with most recent ponyc release
        run: |
          Invoke-WebRequest https://dl.cloudsmith.io/public/ponylang/releases/raw/versions/latest/ponyc-x86-64-pc-windows-msvc.zip -OutFile C:\ponyc.zip;
          Expand-Archive -Path C:\ponyc.zip -DestinationPath C:\ponyc;
          $env:PATH = 'C:\ponyc\bin;' + $env:PATH;
          Invoke-WebRequest https://dl.cloudsmith.io/public/ponylang/releases/raw/versions/latest/corral-x86-64-pc-windows-msvc.zip -OutFile C:\corral.zip;
          Expand-Archive -Path C:\corral.zip -DestinationPath C:\corral;
          $env:PATH = 'C:\corral\bin;' + $env:PATH;
          .\make.ps1 test
